global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Numerics;
global using System.Runtime.InteropServices;
global using AutoCtor;
global using Dalamud.Bindings.ImGui;
global using Dalamud.Game;
global using Dalamud.Hooking;
global using Dalamud.Interface;
global using Dalamud.Interface.Utility;
global using Dalamud.Interface.Utility.Raii;
global using Dalamud.Plugin;
global using Dalamud.Plugin.Services;
global using FFXIVClientStructs.Interop;
global using HaselCommon.Extensions;
global using HaselCommon.Gui;
global using HaselCommon.Services;
global using HaselCommon.Utils;
global using Injectio.Attributes;
global using InteropGenerator.Runtime;
global using InteropGenerator.Runtime.Attributes;
global using Lumina.Excel;
global using Lumina.Excel.Sheets;
global using Lumina.Extensions;
global using Lumina.Text;
global using Lumina.Text.ReadOnly;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using static FFXIVClientStructs.Interop.SpanExtensions;
global using static HaselCommon.Globals.Addon;
global using static HaselDebug.Utils.DebugUtils;
global using Action = System.Action;
global using Color = HaselCommon.Graphics.Color;
global using ExpressionType = Lumina.Text.Expressions.ExpressionType;
global using ItemUtil = Dalamud.Utility.ItemUtil;
global using LinkMacroPayloadType = Lumina.Text.Payloads.LinkMacroPayloadType;
global using MacroCode = Lumina.Text.Payloads.MacroCode;
global using RentedSeStringBuilder = Dalamud.Utility.RentedSeStringBuilder;
global using ValueType = FFXIVClientStructs.FFXIV.Component.GUI.ValueType;
